### ISSUE TITLE
Sonar Runner issue

### ISSUE THREAD

**Issue by vishwnahak** [SonarOpenCommunity/cxx-custom-checks-example-plugin#1]
Hi

Anyone used sonar-runner in Android studio , when I run command "gradle sonarRunner" through terminal it give error as below :
"Can not invoke method public java.lang.Class org.sonar.plugins.surefire.SurefireSensor.dependsUponCoverageSensors()"

My Build.gradle file as below:
apply plugin: 'sonar-runner'

sonarRunner {
sonarProperties {
// can be also set on command line like -Dsonar.analysis.mode=incremental
property "sonar.host.url", "http://myserver.com"
property 'sonar.sourceEncoding', 'UTF-8'
property 'sonar.language', 'java'
property 'sonar.projectKey', 'com.projectKey'
//need to replace with your project package name
property 'sonar.projectName', 'projectName' // need to replace with your project name
property 'sonar.projectVersion', '1.0'
property 'sonar.sources', 'src/main/java'
}
}

If any one have any solution then please help me I am stuck here.

My Android studio version- 1.3.2
SonarQube Runner 2.3
SonarQube Server 5.3

**Comment by jmecosta** [comment]
hi,

supose you should ask this in the sonar gougle groups, this is for c++ source
